name: Create Next.js Project

on:
  push:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    env:
      argument: '--src-dir --app --eslint --tailwind --typescript --import-alias "@/*"'
      projectName: newproject
      nodeVersion: "v20.5.1"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.nodeVersion }}
      - name: Create Next.js Project
        run: |
          corepack enable
          corepack yarn create next-app "${{ env.projectName }}" ${{ env.argument }}
          cd "${{ env.projectName }}"
          corepack yarn set version berry
          corepack yarn
          sed -i 's/^nodeLinker/# nodeLinker/' .yarnrc.yml
          corepack yarn
          curl -kLfsS https://github.com/github/gitignore/raw/main/Node.gitignore >> .gitignore
          corepack yarn dlx @yarnpkg/sdks vscode
          rm -fr .yarn/cache .yarn/unplugged .pnp.*
          cd -
          7z a -mx9 -mmt4 "${{ env.projectName }}.7z" "${{ env.projectName }}"
      - uses: actions/upload-artifact@v3
        with:
          name: "${{ env.projectName }}.7z"
          path: "${{ env.projectName }}.7z"
