name: Create Next.js Project

on:
  push:
  workflow_dispatch:
    inputs:
      projectName:
        description: "Project name"
        required: true
        default: "newproject"
      nodeVersion:
        description: "Node version"
        required: true
        default: "v20.5.1"
      argument:
        description: "Argument"
        required: true
        default: "--src-dir --app --eslint --tailwind --typescript --import-alias \"@/*\""

jobs:
  create:
    runs-on: ubuntu-latest
    env:
      argument: '--src-dir --app --eslint --tailwind --typescript --import-alias "@/*"'
      projectName: newproject
      nodeVersion: "v20.5.1"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.nodeVersion }}
      - name: Set homedir
        id: home
        run: |
          echo "home=$HOME" >> $GITHUB_OUTPUT
      - name: Create Next.js Project
        working-directory: ${{ steps.home.outputs.home }}
        run: |
          corepack enable
          corepack yarn create next-app "${{ env.projectName }}" ${{ env.argument }}
      - name: Set yarn version to berry
        working-directory: "${{ steps.home.outputs.home }}/${{ env.projectName }}"
        run: |
          corepack yarn set version berry
          corepack yarn
          sed -i 's/^nodeLinker/# nodeLinker/' .yarnrc.yml
          export
          corepack yarn
      - name: Fix repo
        working-directory: "${{ steps.home.outputs.home }}/${{ env.projectName }}"
        run: |
          curl -kLfsS https://github.com/github/gitignore/raw/main/Node.gitignore >> .gitignore
          corepack yarn dlx @yarnpkg/sdks vscode
      - name: Compress repo
        working-directory: "${{ steps.home.outputs.home }}"
        run: |
          cd "${{ env.projectName }}"
          rm -fr .yarn/cache .yarn/unplugged .pnp.*
          cd -
          7z a -mx9 -mmt4 "${{ steps.home.outputs.home }}/${{ env.projectName }}.7z" "${{ env.projectName }}"
      - uses: actions/upload-artifact@v3
        with:
          name: "${{ env.projectName }}.7z"
          path: "${{ steps.home.outputs.home }}/${{ env.projectName }}.7z"
